version: "3.8"
services:

  #django:
  #  image: bookstore_django_openapi
  #  build:
  #    context: ./
  #    dockerfile: Dockerfile.django
  #  ports:
  #    - "8001:8001"
      
  client:
    image: bookstore_django_client
    build:
      context: ./
      dockerfile: Dockerfile.react
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - "3001:3000"
    stdin_open: true
    
