version: "3.8"
services:
      
  client:
    image: bookstore_web_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - "80:80"
    environment:
      NODE_ENV: production