FROM python:3

RUN mkdir -p ./api
RUN cd ./api       
RUN git clone https://github.com/ccapeng/bookstore_openapi.git
           
WORKDIR /app

COPY ./api/bookstore_openapi/ .

RUN pip install -r requirements.txt

CMD ["python", "app.py"]