version: "3.8"
services:
      
  client:
    image: bookstore_django_client
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - "3000:3000"
    stdin_open: true